name: Build and Deploy Static Files
on: 
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'        
          
      - name: Install dependencies
        working-directory: EA_Portfolio        
        run: npm install

      - name: Create .env file from secret
        run: echo "${{ secrets.VITE_SECRETS_PROD }}" > EA_Portfolio/.env

      - name: Build the React app
        working-directory: EA_Portfolio
        run: npm run build 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}